language: android
before_install:
  #- sudo apt-get install -y protobuf-compiler
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR/server/src 
  - sudo ./build_ubuntu_1604.sh # build server and generate executable file protoc
  - $TRAVIS_BUILD_DIR/server/src/protobuf/bin/protoc -I$TRAVIS_BUILD_DIR/pb/ --java_out=$TRAVIS_BUILD_DIR/android/app/src/main/java $TRAVIS_BUILD_DIR/pb/*.proto
  - cd $TRAVIS_BUILD_DIR/android/
  - echo y | sdkmanager "build-tools;25.0.0"
  - echo y | sdkmanager "platforms;android-19"
  #- echo y | sdkmanager "ndk-bundle"
before_script:
  - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
android:
  components:
    - build-tools-25
    - android-19
addons:
  artifacts: true
