version: 1.0.{build}
configuration: Release
before_build:
- cmd: >-
    cd .\win-client-2018\include\ProtocolBuffer\
    
    call gen_files_cpp.bat
build:
  project: .\win-client-2018\solution\teamtalk.sln
  parallel: true
  verbosity: quiet
after_build:
- cmd: '"C:\Program Files (x86)\Inno Setup 5\ISCC.exe"  %APPVEYOR_BUILD_FOLDER%\win-client-2018\bin\teamtalk\tt.iss'
artifacts:
- path: .\win-client-2018\mysetup.exe
  name: tt.exe
